from app.db.base_class import Base
from app.models.user_detail import UserDetail
from app.models.user import User
from app.models.language_pair import LanguagePair
from app.models.word import Word
from app.models.pos import POS
from app.models.meaning import Meaning
from app.models.group import Group
from app.models.user_word import UserWord
from app.models.tts import TTS
from app.models.playback_session import PlaybackSession