"""add language and language_pair tables

Revision ID: 6136ab13a22c
Revises: 46ff952dcd77
Create Date: 2025-06-28 16:52:34.742879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6136ab13a22c'
down_revision: Union[str, None] = '46ff952dcd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.add_column('language_pairs', sa.Column('source_lang_id', sa.Integer(), nullable=False))
    op.add_column('language_pairs', sa.Column('target_lang_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'language_pairs', ['source_lang_id', 'target_lang_id'])
    op.create_foreign_key(None, 'language_pairs', 'languages', ['source_lang_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'language_pairs', 'languages', ['target_lang_id'], ['id'], ondelete='CASCADE')
    op.drop_column('language_pairs', 'target_lang')
    op.drop_column('language_pairs', 'source_lang')
    op.add_column('user_details', sa.Column('source_language_id', sa.Integer(), nullable=True))
    op.add_column('user_details', sa.Column('target_language_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_details_active_language_pair_id_fkey', 'user_details', type_='foreignkey')
    op.create_foreign_key(None, 'user_details', 'languages', ['source_language_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_details', 'languages', ['target_language_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_details', 'active_language_pair_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('active_language_pair_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.create_foreign_key('user_details_active_language_pair_id_fkey', 'user_details', 'language_pairs', ['active_language_pair_id'], ['id'])
    op.drop_column('user_details', 'target_language_id')
    op.drop_column('user_details', 'source_language_id')
    op.add_column('language_pairs', sa.Column('source_lang', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('language_pairs', sa.Column('target_lang', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'language_pairs', type_='foreignkey')
    op.drop_constraint(None, 'language_pairs', type_='foreignkey')
    op.drop_constraint(None, 'language_pairs', type_='unique')
    op.drop_column('language_pairs', 'target_lang_id')
    op.drop_column('language_pairs', 'source_lang_id')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
